config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  resources :villages do
    collection { get :search }
    collection { post :upload }
    resources :duplicates
  end
  resources :census_villages do
    collection { post :upload }
  end 
  resources :orders do
    collection { post :compare }
    collection { post :report }
  end

  root 'villages#search'
end

app/models/duplicate.rb
class Duplicate < ApplicationRecord
  belongs_to :village
  belongs_to :duplicate_village, class_name: 'Village'
end

app/controllers/duplicates_controller.rb
class DuplicatesController < ApplicationController
    def index
      @village = Village.find(params[:village_id])
      @duplicates = @village.duplicates
    end
  
    def show
      @village = Village.find(params[:village_id])
      @duplicate = @village.duplicates.find(params[:id])
    end
  
    def new
      @village = Village.find(params[:village_id])
      @duplicate = @village.duplicates.build({ :duplicate_village_id => params[:duplicate_village_id]})
    end
  
    def create
      @village = Village.find(params[:village_id])
      @duplicate = @village.duplicates.build(duplicate_params)
      if @duplicate.save
        redirect_to village_duplicates_path(@village), notice: 'Duplicate was successfully created.'
      else
        render :new
      end
    end
  
    def edit
      @village = Village.find(params[:village_id])
      @duplicate = @village.duplicates.find(params[:id])
    end
  
    def update
      @village = Village.find(params[:village_id])
      @duplicate = @village.duplicates.find(params[:id])
      if @duplicate.update(duplicate_params)
        redirect_to village_duplicates_path(@village), notice: 'Duplicate was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @village = Village.find(params[:village_id])
      @duplicate = @village.duplicates.find(params[:id])
      @duplicate.destroy
      redirect_to village_duplicates_path(@village), notice: 'Duplicate was successfully deleted.'
    end
  
    private
  
    def duplicate_params
      params.require(:duplicate).permit(:duplicate_village_id, :duplicate_type)
    end
  end
  

app/helpers/duplicates_helper.rb
module DuplicatesHelper
end

app/views/duplicates/edit.html.erb
<h1>Edit Duplicate for <%= @village.name %></h1>

<%= form_with(model: [@village, @duplicate], local: true) do |form| %>
  <% if @duplicate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duplicate.errors.count, "error") %> prohibited this duplicate from being saved:</h2>

      <ul>
        <% @duplicate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duplicate_village_id, :class => 'form-label' %>
    <%= form.select :duplicate_village_id, Village.all.collect { |o| [o.name, o.id] }, { include_blank: true }, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :duplicate_type %>
    <%= form.text_field :duplicate_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Duplicates', village_duplicates_path(@village) %>

app/views/duplicates/index.html.erb
<h1>Duplicates for <%= @village.name %></h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Village</th>
            <th scope="col">Sub Division</th>
            <th scope="col">District</th>
            <th scope="col">Order</th>
        </tr>
    </thead>
    <tbody>
    <% @duplicates.each do |duplicate| %>
      <tr>
          <td><%= link_to duplicate.duplicate_village.name, [@village, duplicate] %></td>
          <td><%= duplicate.duplicate_village.subdivision %></td>
          <td><%= duplicate.duplicate_village.district %></td>
          <td><%= duplicate.duplicate_village.order.name %></td>
      </tr>
    <% end %>
    </tbody>
</table>
<%= link_to 'Add', new_village_duplicate_path(@village, @duplicate), :class => 'btn btn-primary' %> 
<%= link_to 'Back to Village', village_path(@village), :class => 'btn btn-outline-primary' %>

app/views/duplicates/new.html.erb
<h1>New Duplicate for <%= @village.name %></h1>

<%= form_with(model: [@village, @duplicate], local: true) do |form| %>
  <% if @duplicate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duplicate.errors.count, "error") %> prohibited this duplicate from being saved:</h2>

      <ul>
        <% @duplicate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duplicate_village_id, :class => 'form-label' %>
    <%= form.select :duplicate_village_id, Village.all.collect { |o| [o.name, o.id] }, { include_blank: true }, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :duplicate_type, :class => 'form-label' %>
    <%= form.text_field :duplicate_type, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Add', :class => 'btn btn-primary' %>
    
    <%= link_to 'Back to Duplicates', village_duplicates_path(@village), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/duplicates/show.html.erb
<p>
  <strong>Duplicate Village ID:</strong>
  <%= @duplicate.duplicate_village_id %>
</p>

<p>
  <strong>Duplicate Type:</strong>
  <%= @duplicate.duplicate_type %>
</p>

<%= link_to 'Edit', edit_village_duplicate_path(@village, @duplicate) %> |
<%= link_to 'Back to Duplicates', village_duplicates_path(@village) %>