config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  resources :villages do
    collection { get :search }
    collection { post :upload }
    resources :duplicates
  end
  resources :census_villages do
    collection { post :upload }
  end 
  resources :orders do
    collection { post :compare }
    collection { post :report }
  end

  root 'villages#search'
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :villages
end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
      @orders_all = Order.all
      @orders = @orders_all.order(:date).page params[:page]
    end
  
    def show
      @order = Order.find(params[:id])
      @villages = @order.villages.order(:district, :subdivision, :name).page params[:page]
    end
  
    def new
      @order = Order.new
    end

    def compare
      @order1 = Order.find(params[:order1_id])
      @order2 = Order.find(params[:order2_id])

    end

    def report
      @order1 = Order.find(params[:order1_id])
      @order2 = Order.find(params[:order2_id])
      @order3 = Order.find(params[:order3_id])
      @order4 = Order.find(params[:order4_id])

      @matching_data = []
      matched_villages_order1 = []
      matched_villages_order2 = []
      matched_villages_order3 = []
      matched_villages_order4 = []

      CensusVillage.find_each do |census_village|
        dupe_villages = Village.with_similar_name(census_village.name, 0).where(order_id: @order1.id).limit(1)
        if dupe_villages.empty?
          matched_village_order1 = nil
        else
          matched_villages_order1 << dupe_villages[0].id
          matched_village_order1= dupe_villages[0].name
        end

        dupe_villages2 = Village.with_similar_name(census_village.name, 0).where(order_id: @order2.id).limit(1)
        if dupe_villages2.empty?
          matched_village_order2 = nil
        else
          matched_villages_order2 << dupe_villages2[0].id
          matched_village_order2= dupe_villages2[0].name
        end

        dupe_villages3 = Village.with_similar_name(census_village.name, 0).where(order_id: @order3.id).limit(1)
        if dupe_villages3.empty?
          matched_village_order3 = nil
        else
          matched_villages_order3 << dupe_villages3[0].id
          matched_village_order3 = dupe_villages3[0].name
        end

        dupe_villages4 = Village.with_similar_name(census_village.name, 0).where(order_id: @order4.id).limit(1)
        if dupe_villages4.empty?
          matched_village_order4 = nil
        else
          matched_villages_order4 << dupe_villages4[0].id
          matched_village_order4= dupe_villages4[0].name
        end

        @matching_data << {
          subdivision: census_village.subdivision,
          district: census_village.district,
          census_village: census_village.name,
          matched_village_order1: matched_village_order1,
          matched_village_order2: matched_village_order2,
          matched_village_order3: matched_village_order3,
          matched_village_order4: matched_village_order4
        }
      end

      @order1.villages.where.not(id: matched_villages_order1).find_each do |unmatched_village|
        dupe_villages2 = Village.with_similar_name(unmatched_village.name, 0).where(order_id: @order2.id).limit(1)
        if dupe_villages2.empty?
          matched_village_order2 = nil
        else
          matched_villages_order2 << dupe_villages2[0].id
          matched_village_order2= dupe_villages2[0].name
        end

        dupe_villages3 = Village.with_similar_name(unmatched_village.name, 0).where(order_id: @order3.id).limit(1)
        if dupe_villages3.empty?
          matched_village_order3 = nil
        else
          matched_villages_order3 << dupe_villages3[0].id
          matched_village_order3 = dupe_villages3[0].name
        end

        dupe_villages4 = Village.with_similar_name(unmatched_village.name, 0).where(order_id: @order4.id).limit(1)
        if dupe_villages4.empty?
          matched_village_order4 = nil
        else
          matched_villages_order4 << dupe_villages4[0].id
          matched_village_order4= dupe_villages4[0].name
        end

        @matching_data << {
          subdivision: unmatched_village.subdivision,
          district: unmatched_village.district,
          census_village: nil,
          matched_village_order1: unmatched_village.name,
          matched_village_order2: matched_village_order2,
          matched_village_order3: matched_village_order3,
          matched_village_order4: matched_village_order4
        }
      end
      
      @order2.villages.where.not(id: matched_villages_order2).find_each do |unmatched_village|
        dupe_villages3 = Village.with_similar_name(unmatched_village.name, 0).where(order_id: @order3.id).limit(1)
        if dupe_villages3.empty?
          matched_village_order3 = nil
        else
          matched_villages_order3 << dupe_villages3[0].id
          matched_village_order3 = dupe_villages3[0].name
        end

        dupe_villages4 = Village.with_similar_name(unmatched_village.name, 0).where(order_id: @order4.id).limit(1)
        if dupe_villages4.empty?
          matched_village_order4 = nil
        else
          matched_villages_order4 << dupe_villages4[0].id
          matched_village_order4= dupe_villages4[0].name
        end

        @matching_data << {
          subdivision: unmatched_village.subdivision,
          district: unmatched_village.district,
          census_village: nil,
          matched_village_order1: nil,
          matched_village_order2: unmatched_village.name,
          matched_village_order3: matched_village_order3,
          matched_village_order4: matched_village_order4
        }
      end

      @order3.villages.where.not(id: matched_villages_order3).find_each do |unmatched_village|
        dupe_villages4 = Village.with_similar_name(unmatched_village.name, 0).where(order_id: @order4.id).limit(1)
        if dupe_villages4.empty?
          matched_village_order4 = nil
        else
          matched_villages_order4 << dupe_villages4[0].id
          matched_village_order4= dupe_villages4[0].name
        end

        @matching_data << {
          subdivision: unmatched_village.subdivision,
          district: unmatched_village.district,
          census_village: nil,
          matched_village_order1: nil,
          matched_village_order2: nil,
          matched_village_order3: unmatched_village.name,
          matched_village_order4: matched_village_order4
        }
      end

      @order4.villages.where.not(id: matched_villages_order4).find_each do |unmatched_village|
        @matching_data << {
          subdivision: unmatched_village.subdivision,
          district: unmatched_village.district,
          census_village: nil,
          matched_village_order1: nil,
          matched_village_order2: nil,
          matched_village_order3: nil,
          matched_village_order4: unmatched_village.name
        }
      end

      respond_to do |format|
        format.html
        format.csv
      end
    end

    def report_csv
      CSV.generate do |csv|
        csv << %w{ id created_at order_type order_price }
        all.each do |order|
          csv << [order.id, order.ctreated_at, order.order_type, order.order_price ]
        end
      end
    end

    def create
      @order = Order.new(order_params)
      if @order.save
        flash[:success] = "Order was successfully created."
        redirect_to @order
      else
        render :new
      end
    end
  
    def edit
      @order = Order.find(params[:id])
    end
  
    def update
      @order = Order.find(params[:id])
      if @order.update(order_params)
        flash[:success] = "Order was successfully updated."
        redirect_to orders_path
      else
        render :edit
      end
    end
  
    def destroy
      @order = Order.find(params[:id])
      @order.destroy
      flash[:success] = "Order was successfully deleted."
      redirect_to orders_path
    end
  
    private
  
    def order_params
      params.require(:order).permit(:name, :date)
    end
  end
  

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/compare.html.erb
<h1>Details of Order</h1>


<dl class="dl-horizontal">
  <dt>Order 1</dt>
  <dd><%= @order1.name %></dd>
  <dt>Order 2</dt>
  <dd><%= @order2.name %></dd>
</dl>

<h4>Possible duplicate villages of order2 in order 1</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Main Village</th>    
            <th scope="col">Subdivision</th>
            <th scope="col">Possible Duplicate</th> 
            <th scope="col">Possible Duplicate 2</th> 
            <th scope="col">Possible Duplicate 3</th> 
        </tr>
    </thead>
    <tbody>
    <% @order1.villages.each do |village| %>
      <tr>
          <td><%= village.name %></td>
          <td><%= village.subdivision %></td>
          <% poss_dupes = 0 %>
          <% dupe_villages = Village.with_similar_name(village.name, village.id).where(order_id: @order2.id).limit(3) %>
          <% dupe_villages.each do |dupe_village| %>
            
            <td><%= dupe_village.name %></td>
            <% poss_dupes += 1%>
          <% end %>
          <% while poss_dupes < 3 %>
            <% poss_dupes += 1 %>
            <td></td>
          <% end %>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= form_with(model: @order, local: true) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, :class => 'form-label' %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :date, :class => 'form-label' %>
    <%= form.text_field :date, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', :class => 'btn btn-primary' %>
    <%= link_to 'Back', orders_path, :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Order Details</th>
            <th scope="col">Date of Order</th>
            <th scope="col">Number of Villages in Order</th>
        </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr>
          <td><%= link_to order.name, order_path(order) %></td>
          <td><%= order.date %></td>
          <td><%= order.villages.count %></td>
      </tr>
    <% end %>
    </tbody>
</table>

<%= paginate @orders %>

<%= link_to 'Add New Order', new_order_path, :class => 'btn btn-primary' %>

<%= form_with url: compare_orders_path, local: true do |form| %>
    <div class="mb-3 mt-3">
      <%= form.label :order1, :class => 'form-label' %>
      <%= form.collection_select :order1_id, @orders_all, :id, :name, include_blank: true %>
    </div>
    <div class="mb-3">
      <%= form.label :order2, :class => 'form-label' %>
      <%= form.collection_select :order2_id, @orders_all, :id, :name, include_blank: true %>
    </div>
    <div class="actions">
      <%= form.submit "Compare", :class => 'btn btn-primary'  %>
    </div>
<% end %>


<%= form_with url: report_orders_path(:format => 'csv'), local: true do |form| %>
    <div class="mb-3 mt-3">
      <%= form.label :order1, :class => 'form-label' %>
      <%= form.collection_select :order1_id, @orders_all, :id, :name, include_blank: true %>
    </div>
    <div class="mb-3">
      <%= form.label :order2, :class => 'form-label' %>
      <%= form.collection_select :order2_id, @orders_all, :id, :name, include_blank: true %>
    </div>
    <div class="mb-3">
      <%= form.label :order3, :class => 'form-label' %>
      <%= form.collection_select :order3_id, @orders_all, :id, :name, include_blank: true %>
    </div>
    <div class="mb-3">
      <%= form.label :order4, :class => 'form-label' %>
      <%= form.collection_select :order4_id, @orders_all, :id, :name, include_blank: true %>
    </div>
    <div class="actions">
      <%= form.submit "Generate Report", :class => 'btn btn-primary'  %>
    </div>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_with(model: @order, local: true) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, :class => 'form-label' %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :date, :class => 'form-label' %>
    <%= form.date_field :date, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Add order", :class => 'btn btn-primary' %>
    <%= link_to 'Back', orders_path, :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/orders/report.csv.erb
<%- headers = ['Subdivision', 'District', 'Census', 'Order 1', 'Order 2', 'Order 3', 'Order 4'] -%>
<%= CSV.generate_line headers %>
<%- @matching_data.each do |row| -%>
  <%= CSV.generate_line([row[:subdivision], row[:district], row[:census_village], row[:matched_village_order1], row[:matched_village_order2], row[:matched_village_order3], row[:matched_village_order4]]) -%>
<%- end -%>

app/views/orders/report.html.erb
<h1>Details of Order</h1>


<dl class="dl-horizontal">
  <dt>Order 1</dt>
  <dd><%= @order1.name %></dd>
  <dt>Order 2</dt>
  <dd><%= @order2.name %></dd>
</dl>

<h4>Possible duplicate villages of order2 in order 1</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">CensusVillage</th>    
            <th scope="col">Order 1 Village</th>
            <th scope="col">Order 2 Village</th>
            <th scope="col">Order 3 Village</th>
            <th scope="col">Order 4 Village</th>
        </tr>
    </thead>
    <tbody>
    <% @matching_data.each do |row| %>
      <tr>
          <td><%= row[:census_village] %></td>
          <td><%= row[:matched_village_order1] %></td>
          <td><%= row[:matched_village_order2] %></td>
          <td><%= row[:matched_village_order3] %></td>
          <td><%= row[:matched_village_order4] %></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/orders/show.html.erb
<h1>Details of Order</h1>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @order.name %></dd>
  <dt>Date of Order</dt>
  <dd><%= @order.date %></dd>
  <dt>Order ID</dt>
  <dd><%= @order.id %></dd>

  <%= link_to 'Edit', edit_order_path(@order), :class => 'btn btn-primary' %>
  <%= link_to 'Back', orders_path, :class => 'btn btn-outline-primary' %>
</dl>


<h4 class="navbar">Villages</h4>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Village</th>
            <th scope="col">Present Sub Division</th>
            <th scope="col">Present District</th>
            <th scope="col">Sub Division</th>
            <th scope="col">District</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody id="village-list">
  <% @villages.each do |village| %>
        <tr>
            <td><%= link_to village.name, village_path(village) %></td>
            <td><%= village.subdivision_present %></td>
            <td><%= village.district_present %></td>
            <td><%= village.subdivision %></td>
            <td><%= village.district %></td>
            <td></td>
            
        </tr>
  <% end %>
    </tbody>
</table>

<%= paginate @villages %>

<%= form_with url: upload_villages_path, local: true, multipart: true do |form| %>
  <div class="mb-3">
    <span>Upload a csv file having columns name, subdivision and district</span>
    <%= form.label :file, :class => 'form-label' %>
    <%= form.hidden_field :order_id, :value => @order.id %>
    <%= form.file_field :file , :class => 'form-control'%>
  </div>
  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>