config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  resources :villages do
    collection { get :search }
    collection { post :upload }
    resources :duplicates
  end
  resources :census_villages do
    collection { post :upload }
  end 
  resources :orders do
    collection { post :compare }
    collection { post :report }
  end

  root 'villages#search'
end

app/models/village.rb
class Village < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :census_village, optional: true
  has_many :lgd_villages
  has_many :duplicates
  has_many :duplicate_villages, through: :duplicates, source: :duplicate_village

  scope :with_similar_name, ->(name, id) {
    select("villages.*, similarity(name, '#{sanitize_sql(name)}') AS similarity_score")
      .where("similarity(name, ?) > 0.45 and id != ?", name, id)
      .order("similarity_score DESC")
  }

end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
    def index
      @villages = Village.where("name ILIKE ?", "%#{params[:name]}%")
      @villages = @villages.where("subdivision ILIKE ?", "%#{params[:subdivision]}%")
      @villages = @villages.where("district ILIKE ?", "%#{params[:district]}%")
      @villages = @villages.order(:district, :subdivision, :name).page params[:page]
    end
  
    def show
      @village = Village.find(params[:id])
      @similar_villages = Village.with_similar_name(@village.name, @village.id)
      @similar_census_villages = CensusVillage.with_similar_name(@village.name)
    end
  
    def search
      @villageName = params[:name]
      @similar_villages = Village.with_similar_name(@villageName, 0)
      @similar_census_villages = CensusVillage.with_similar_name(@villageName)
    end

    def new
      @village = Village.new
    end
  
    def create
      @village = Village.new(village_params)
      if @village.save
        flash[:success] = "Village was successfully created."
        redirect_to villages_path
      else
        render 'new'
      end
    end
  
    def edit
      @village = Village.find(params[:id])
      unless params[:census_village_id].nil?
        @village.census_village = CensusVillage.find(params[:census_village_id])
      end
      
    end
  
    def update
      @village = Village.find(params[:id])
      
      if @village.update(village_params)
        flash[:success] = "Village was successfully updated."
        redirect_to villages_path
      else
        render 'edit'
      end
    end

    def upload
      file = params[:file]
      order = nil
      unless params['order_id'].nil? 
        order = Order.find(params['order_id'])
      end

      if file
        CSV.foreach(file.path, headers: true) do |row|
          Village.create!(
            name: row['name'],
            subdivision: row['subdivision'],
            district: row['district'],
            subdivision_present: row['subdivision_present'],
            district_present: row['district_present'],
            order: order
          )
        end

        flash[:success] = "CSV file successfully uploaded and processed."
      else
        flash[:error] = "Please upload a valid CSV file."
      end
      
      redirect_to order_path(order)
    end
  
    def destroy
      @village = Village.find(params[:id])
      @village.destroy
      redirect_to villages_path
    end
  
    private
  
    def village_params
      params.require(:village).permit(:name, :subdivision, :district, :subdivision_present, :district_present, :order_id, :census_village_id, :remarks, :hamlet)
    end
  end
  

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/edit.html.erb
<h1>Edit Village</h1>

<%= form_with(model: @village, local: true) do |form| %>
  <% if @village.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
        <% @village.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, :class => 'form-label' %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :subdivision, :class => 'form-label' %>
    <%= form.text_field :subdivision, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :district, :class => 'form-label' %>
    <%= form.text_field :district, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :subdivision_present, :class => 'form-label' %>
    <%= form.text_field :subdivision_present, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :district_present, :class => 'form-label' %>
    <%= form.text_field :district_present, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :order_id, :class => 'form-label' %>
    <%= form.select :order_id, Order.all.collect { |o| [o.name, o.id] }, { include_blank: true }, :class => 'form-control' %>
  </div>
  
  <div class="mb-3">
    <%= form.label :census_village_id, :class => 'form-label' %>
    <%= form.select :census_village_id, CensusVillage.all.collect { |o| [o.name, o.id] }, { include_blank: true }, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :remarks, :class => 'form-label' %>
    <%= form.text_area :remarks, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :hamlet, :class => 'form-label' %>
    <%= form.checkbox :hamlet, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', :class => 'btn btn-primary' %>
    <%= link_to 'Back', villages_path, :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/villages/index.html.erb
<h1 class="navbar">Villages</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Village</th>
            <th scope="col">Present Sub Division</th>
            <th scope="col">Present District</th>
            <th scope="col">Sub Division</th>
            <th scope="col">District</th>
            <th scope="col"></th>
        </tr>
        <%= form_with url: villages_path, method: :get, local: true do |form| %>
        <tr>
            <th scope="col"><%= text_field_tag :name, params[:name], placeholder: "Filter by name" %></th>
            <th scope="col"><%= text_field_tag :subdivision_present, params[:subdivision_present], placeholder: "Filter by present subdivision" %></th>
            <th scope="col"><%= text_field_tag :district_present, params[:district_present], placeholder: "Filter by present district" %></th>
            <th scope="col"><%= text_field_tag :subdivision, params[:subdivision], placeholder: "Filter by subdivision" %></th>
            <th scope="col"><%= text_field_tag :district, params[:district], placeholder: "Filter by district" %></th>
            <th scope="col"><%= submit_tag "Filter", :class => 'btn btn-primary' %></th> 
        </tr>
        <% end %>
    </thead>
    <tbody id="village-list">
  <% @villages.each do |village| %>
        <tr>
            <td title="<%= village.order.name %>"><%= link_to village.name, village_path(village), title: village.order.name %></td>
            <td><%= village.subdivision_present %></td>
            <td><%= village.district_present %></td>
            <td><%= village.subdivision %></td>
            <td><%= village.district %></td>
            <td></td>
            
        </tr>
  <% end %>
    </tbody>
</table>

<%= paginate @villages %>

<div>
  <%= link_to 'Add New Village', new_village_path, :class => 'btn btn-primary' %>
</div>

app/views/villages/new.html.erb
<h1>New Village</h1>

<%= form_with(model: @village, local: true) do |form| %>
  <% if @village.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
        <% @village.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, :class => 'form-label' %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :subdivision, :class => 'form-label' %>
    <%= form.text_field :subdivision, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :district, :class => 'form-label' %>
    <%= form.text_field :district, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :subdivision_present, :class => 'form-label' %>
    <%= form.text_field :subdivision_present, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :district_present, :class => 'form-label' %>
    <%= form.text_field :district_present, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :order_id, :class => 'form-label' %>
    <%= form.select :order_id, Order.all.collect { |o| [o.name, o.id] }, { include_blank: true }, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :census_village_id, :class => 'form-label' %>
    <%= form.select :census_village_id, CensusVillage.all.collect { |o| [o.name, o.id] }, { include_blank: true }, :class => 'form-control' %>
  </div>
  
  <div class="actions">
    <%= form.submit 'Add', :class => 'btn btn-primary' %>
    <%= link_to 'Back', villages_path, :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/villages/search.html.erb
<h1 class="navbar">Search for Villages</h1>

<%= form_with url: search_villages_path, method: :get, local: true do |form| %>
  <div class="input-group mb-3">
    <%= text_field_tag :name, params[:name], placeholder: "Village Name", class: "form-control" %>
    <div class="input-group-append">
      <%= submit_tag "Search", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<h2>Census Villages</h2>
<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Census Village</th>
          <th scope="col">Sub Division</th>
          <th scope="col">District</th>
          <th scope="col">Code</th>
          <th scope="col"></th>
      </tr>
  </thead>
  <tbody>
  <% @similar_census_villages.each do |similar_census_village| %>
    <tr>
        <td><%= link_to similar_census_village.name, census_village_path(similar_census_village) %></td>
        <td><%= similar_census_village.subdivision %></td>
        <td><%= similar_census_village.district %></td>
        <td><%= similar_census_village.code %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<h2>Villages</h2>
<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Village</th>
          <th scope="col">Sub Division</th>
          <th scope="col">District</th>
          <th scope="col">Order</th>
      </tr>
  </thead>
  <tbody>
  <% @similar_villages.each do |similar_village| %>
    <tr>
        <td><%= link_to similar_village.name, village_path(similar_village) %></td>
        <td><%= similar_village.subdivision %></td>
        <td><%= similar_village.district %></td>
        <td><%= similar_village.order.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>  

<div>
  <%= link_to 'Add New Village', new_village_path, :class => 'btn btn-primary' %>
</div>

app/views/villages/show.html.erb
<h1>Details of Village <%= @village.name %></h1>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @village.name %></dd>
  <dt>Present Sub Division</dt>
  <dd><%= @village.subdivision_present %></dd>
  <dt>Present District</dt>
  <dd><%= @village.district_present %></dd>
  <dt>Sub Division</dt>
  <dd><%= @village.subdivision %></dd>
  <dt>District</dt>
  <dd><%= @village.district %></dd>
  <dt>Census Village</dt>
  <dd><%= @village.census_village.nil? ? "Not assigned" : @village.census_village.name %></dd>
    <dt>Order</dt>
  <dd><%= @village.order.name %></dd>
  <dt>Remarks</dt>
  <dd><%= @village.remarks %></dd>
    <dt>Is Hamlet</dt>
  <dd><%= @village.hamlet %></dd>
  <%= link_to 'See duplicates', village_duplicates_path(@village), :class => 'btn btn-outline-primary' %>
</dl>

<h2>Possible Census Villages</h2>
<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Census Village</th>
          <th scope="col">Sub Division</th>
          <th scope="col">District</th>
          <th scope="col">Code</th>
          <th scope="col"></th>
      </tr>
  </thead>
  <tbody>
  <% @similar_census_villages.each do |similar_census_village| %>
    <tr>
        <td><%= link_to similar_census_village.name, census_village_path(similar_census_village) %></td>
        <td><%= similar_census_village.subdivision %></td>
        <td><%= similar_census_village.district %></td>
        <td><%= similar_census_village.code %></td>
        <td><%= link_to 'Add to Census Village', edit_village_path(@village, :census_village_id => similar_census_village.id ), :class => 'btn btn-primary' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<h2>Possible duplicates</h2>
<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Village</th>
          <th scope="col">Sub Division</th>
          <th scope="col">District</th>
          <th scope="col">Present Sub Division</th>
          <th scope="col">Present District</th>
          <th scope="col"></th>
      </tr>
  </thead>
  <tbody>
  <% @similar_villages.each do |similar_village| %>
    <tr>
        <td><%= link_to similar_village.name, village_path(similar_village) %></td>
        <td><%= similar_village.subdivision %></td>
        <td><%= similar_village.district %></td>
        <td><%= similar_village.subdivision_present %></td>
        <td><%= similar_village.district_present %></td>
        
        <td><%= link_to 'Add as duplicate', new_village_duplicate_path(@village, :duplicate_village_id => similar_village.id ), :class => 'btn btn-primary' %></td>

    </tr>
  <% end %>
  </tbody>
</table>  

<%= link_to 'Edit', edit_village_path(@village), :class => 'btn btn-primary' %>
<%= link_to 'Back', villages_path, :class => 'btn btn-outline-primary' %>