config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  resources :villages do
    collection { get :search }
    collection { post :upload }
    resources :duplicates
  end
  resources :census_villages do
    collection { post :upload }
  end 
  resources :orders do
    collection { post :compare }
    collection { post :report }
  end

  root 'villages#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Villages" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Villages', villages_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', orders_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Census Villages', census_villages_path, :class => 'nav-link' %>
              </li>
            </ul>
          </div>
          <%= form_with url: search_villages_path, method: :get, local: true do |form| %>
            <%= text_field_tag :name, params[:name], placeholder: "Village Name" %>
            <th scope="col"><%= submit_tag "Search", :class => 'btn btn-primary' %></th> 
          <% end %>
          <h5 class="navbar-brand my-2 my-md-0 mr-md-3">Land Resources Department</h5>
        </div>
      </nav>
      <div id="flash-messages">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>">
            <%= message %>
          </div>
        <% end %>
      </div>
      
        <%= yield %>
    </div>
  </body>
</html>